---
language: python
python: "3.6"

# Use the new container infrastructure
sudo: false

addons:
  apt:
    packages:
    - python-pip

install:
  # Install dependences
  - make install env=test

script:
  - make lint
  - make test
