name: build and deploy resume

on:
  push:
    branches:
      - develop
env:
  IMAGE: hadenlabs/xelatex:18.04

# docker run --rm -it -v "${PWD}":/data hadenlabs/xelatex:18.04 -output-directory=./ resume.tex

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: build resume
        run: |
          docker run --rm -it -v "${PWD}":/data ${{ env.IMAGE }} -output-directory=./ resume.tex -file-line-error -interaction=nonstopmode
