name: build and deploy resume

on:
  push:
    branches:
      - develop
env:
  IMAGE: hadenlabs/xelatex:18.04

jobs:
  build:
    runs-on: Ubuntu-20.04
    container:
      image: ${{ env.IMAGE }}
      volumes:
        - $pwd:/root
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: build resume
        run: |
          xelatex -output-directory=./ resume.tex -file-line-error -interaction=nonstopmode
