name: create-resume

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  resume:
    runs-on: Ubuntu-20.04
    container:
      image: hadenlabs/xelatex:18.04
    steps:
      - name: checkout
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2
        with:
          path: 'resume'
      - name: build resume
        run: |
          xelatex -output-directory=./ resume.tex -file-line-error -interaction=nonstopmode
      - name: commit resume pdf
        if: ${{ !env.ACT }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'ci: generate resume'
          branch: develop
          commit_options: '--no-verify --signoff'
          commit_user_name: '@slovacus'
          commit_user_email: 'slovacus@gmail.com'
          commit_author: 'slovacus <slovacus@gmail.com>'
