name: create-resume

on:
  workflow_run:
    workflows:
      - lint-code
    types:
      - completed

  push:
    branches:
      - develop
      - main

    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      # https://semver.org/ proper release tags, more or less
      - 'v[0-9]+.[0-9]+.[0-9]+'
      # prerelease tags, more or less
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  resume:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out a copy of the repo
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Make Resume
        run: task xelatex:resume

      - name: Commit resume pdf
        if: ${{ !env.ACT }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'ci: generate resume'
          commit_options: '--no-verify --signoff'
          commit_user_name: 'Luis Mayta'
          commit_user_email: 'luis@hadenlabs.com'
          commit_author: 'Luis Mayta <luis@hadenlabs.com>'
